name: Website-Deploy-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Node.js Env
      uses: actions/setup-node@v1
      
    - name: Build
      run: |
        cd personal-website
        npm run build
    
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        source: "build/*"
        target: "~/personal-website/"
      
